"""Implemented products model

Revision ID: 18ede4a2ee5c
Revises: None
Create Date: 2016-02-09 20:15:46.491975

"""

# revision identifiers, used by Alembic.
revision = '18ede4a2ee5c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Unicode(length=100), nullable=False),
    sa.Column('manufacturer', sa.Unicode(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    ### end Alembic commands ###
