"""Added image url column in Product model

Revision ID: b9d522de8967
Revises: 18ede4a2ee5c
Create Date: 2016-02-09 22:25:05.709782

"""

# revision identifiers, used by Alembic.
revision = 'b9d522de8967'
down_revision = '18ede4a2ee5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.Unicode(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    ### end Alembic commands ###
